import React, { useEffect, useState } from 'react'
import { TodoProvider } from './context/TodoContext'
import TodoForm from './Components/TodoForm'
import TodoItem from './Components/TodoItem'

const App = () => {

  const [todos, setTodos] = useState(() => {
    try {
      const storedTodos = JSON.parse(localStorage.getItem("todos"));
      return storedTodos ? storedTodos : [];
    } catch (error) {
      console.error("Error reading todos from localStorage", error);
      return [];
    }
  }); // useeffect to avoid cascade rendering and also to get the todos from local storage when the component mounts and we are using a function to set the initial state of todos so that it only runs once when the component mounts and not on every render

  const addTodo = (todo) => {
    setTodos((prev) => [...prev,{...todo,id:Date.now()}]); // why spread ...todo because we want to add the new todo to the existing todos and we also want to add an id to the new todo which is generated by Date.now()
  }
  // t is the current todo in the loop and if the id matches then we update the todo else we return the same todo
  const updatedTodo = (id,todo) => {
    setTodos((prev) => prev.map((t) => t.id === id ? {...t,...todo} : t));
  }

  const deleteTodo = (id) => {
    setTodos((prev) => prev.filter((t) => t.id !== id));
  }

  const toggleComplete = (id) => {
    setTodos((prev) => prev.map((t) => t.id === id ? {...t,isCompleted: !t.isCompleted} : t));
  }

  // Removed previous useEffect for getting items to prevent race condition with local storage.

  useEffect(() => {
    localStorage.setItem("todos",JSON.stringify(todos)); // we are setting the todos in local storage and stringifying it to store it as a string
  },[todos]) // we are using the todos state as a dependency so that whenever the todos state changes we update the local storage with the new todos


  return (
    <TodoProvider value={{todos,addTodo,updatedTodo,deleteTodo,toggleComplete}}>
    <div className="bg-[#172842] min-h-screen py-8">
      <div className="w-full max-w-2xl mx-auto shadow-md rounded-lg px-4 py-3 text-white">
          <h1 className="text-2xl font-bold text-center mb-8 mt-2">Manage Your Todos</h1>
          <div className="mb-4">
              {/* Todo form goes here */} 
              <TodoForm />
          </div>
          <div className="flex flex-wrap gap-y-3">
              {/*Loop and Add TodoItem here */}
              {todos.map((todo)=>(
                <TodoItem className="w-full" key={todo.id} todo={todo} />
              ))}
          </div>
      </div>
  </div>
    </TodoProvider>
  )
}

export default App